apiVersion: v1
kind: Pod
metadata:
  name: longnh30-app
spec:
  containers:
    - name: longnh30-app
      image: 013268759557.dkr.ecr.ap-southeast-1.amazonaws.com/udacity-project-4:latest
  imagePullSecrets:
    - name: longnh30-secret-ecr